Models/ErrorViewModel.cs
namespace MyToDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ToDoTask.cs
using Microsoft.AspNetCore.Identity;
using MyToDo.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyToDo.Models
{
    public class ToDoTask
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        [Display(Name = "Status")]
        public byte? StatusCode { get; set; }
        [Display(Name="Due date")]
        public DateOnly? DueDate { get; set; }

        [Required]
        public string? UserId { get; set; }
        [ForeignKey("UserId")]
        public IdentityUser? User { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyToDo.Models;
using System.Diagnostics;

namespace MyToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ToDoTasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using MyToDo.Data;
using MyToDo.Enums;
using MyToDo.Models;
using System.Security.Claims;


namespace MyToDo.Controllers
{
    [Authorize]
    public class ToDoTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ToDoTasksController(ApplicationDbContext context) { _context = context; }

        public async Task<IActionResult> Index(List<byte> status)
        {
            if (status == null || status.Count == 0)
            {
                var model = await _context.Tasks.
                    Where(t => (t.UserId == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value) && ((t.StatusCode == (byte)ToDoStates.ToDo) || (t.StatusCode == (byte)ToDoStates.InProgress)))
                    .OrderBy(t => t.DueDate).ToListAsync();

                return View(model);
            }
            else
            {
                ViewData["CurrentStatusFilters"] = status;
                var model = await _context.Tasks.
                    Where(t => (t.UserId == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value) && (status.Contains((byte)t.StatusCode)))
                    .OrderBy(t => t.DueDate).ToListAsync();

                return View(model);
            }
        }

        // GET request
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Name, Description, StatusCode, DueDate, UserId")] ToDoTask task)
        {
            if (ModelState.IsValid)
            {
                _context.Add(task);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(task);
        }

        // GET request
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ToDoTask task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound(); // may be change to task does not exist
            }
            if (task.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound(); // may be change to access deny
            }
            return View(task);
        }

        // POST request
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Description, StatusCode, DueDate, UserId")] ToDoTask task)
        {
            if (id != task.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Tasks.Update(task);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (IsTaskExist(id))
                    {
                        throw;
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(task); // doesn't really obvious when something went wrong
        }

        // GET request
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // ToDoTask task = await _context.Tasks.FindAsync(id);
            ToDoTask task = await _context.Tasks
                .Include(t => t.User)
                .FirstOrDefaultAsync(tk => tk.Id == id); // a little bit strange but will try
            if (task == null)
            {
                return NotFound(); // May be change to the task does not exist
            }
            if (task.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound(); // May be change to access denied
            }
            return View(task);
        }

        // POST request
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            ToDoTask? task = await _context.Tasks.FindAsync(id);
            if (task != null) // May be add task is already deleted
            {
                _context.Tasks.Remove(task);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ChangeStatus(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            ToDoTask task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            if (task.StatusCode != (byte)2) task.StatusCode++; // May be add "already done message"
            _context.Tasks.Update(task);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
            
        }

        public bool IsTaskExist(int id)
        {
            return _context.Tasks.Any(task => task.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">MyToDo List</h1>
    <p></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoTasks" asp-action="Index">MyToDo list</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ToDoTasks/Create.cshtml
@model MyToDo.Models.ToDoTask
@using Microsoft.AspNetCore.Identity
@using MyToDo.Enums
@inject UserManager<IdentityUser> userManager;

@{
    
}

<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name:</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description:</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div form-group>
                <label asp-for="StatusCode" class="control-label">Task status:</label>
                <select asp-for="StatusCode" class="form-control">
                    <option value="@((int)ToDoStates.ToDo)">@ToDoStates.ToDo</option>
                    <option value="@((int)ToDoStates.InProgress)">@ToDoStates.InProgress</option>
                    <option value="@((int)ToDoStates.Done)">@ToDoStates.Done</option>
                </select>
                <span asp-validation-for="StatusCode" class="text-danger"></span>
            </div>
            <div class="mt-1" form-group>
                <label asp-for="DueDate" class="control-label">Due date:</label>
                <input asp-for="DueDate" type="date" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" class="form-control" value="@userManager.GetUserId(User)"/>
            </div>
            <div class="form-group" >
                <input class="mt-2" type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a class="btn btn-info mt-2" asp-action="Index">Back to the list</a>
</div>

Views/ToDoTasks/Delete.cshtml
@model MyToDo.Models.ToDoTask
@using Microsoft.AspNetCore.Identity
@using MyToDo.Enums
@inject UserManager<IdentityUser> userManager;

@{
}

<h1>Delete</h1>
<h3>Are  you sure you want to delete this task?</h3>

<div>
    <h4>Task</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusCode)
        </dt>
        <dd class="col-sm-10">
            @Enum.GetName(typeof(ToDoStates), Model.StatusCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input class="btn btn-danger" type="Submit" value="Delete" />
        <a class="btn btn-info" asp-action="Index">Back to the list</a>
    </form>
</div>

Views/ToDoTasks/Edit.cshtml
@model MyToDo.Models.ToDoTask
@using MyToDo.Enums
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> userManager;

@{
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name:</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description:</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div form-group>
                <label asp-for="StatusCode" class="control-label">Task status:</label>
                <select asp-for="StatusCode" class="form-control">
                    <option value="@((int)ToDoStates.ToDo)">@ToDoStates.ToDo</option>
                    <option value="@((int)ToDoStates.InProgress)">@ToDoStates.InProgress</option>
                    <option value="@((int)ToDoStates.Done)">@ToDoStates.Done</option>
                </select>
                <span asp-validation-for="StatusCode" class="text-danger"></span>
            </div>
            <div class="mt-1" form-group>
                <label asp-for="DueDate" class="control-label">Due date:</label>
                <input asp-for="DueDate" type="date" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" class="form-control" value="@userManager.GetUserId(User)" />
            </div>
            <div class="form-group">
                <input class="mt-2" type="submit" value="Edit" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a class="btn btn-info mt-2" asp-action="Index">Back to the list</a>
</div>

Views/ToDoTasks/Index.cshtml
@model List<MyToDo.Models.ToDoTask>
@using MyToDo.Enums

<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My ToDo List</title>
    <style>
        /* Basic Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            padding: 20px;
        }

        h1 {
            text-align: center;
            color: #4a90e2;
            margin-bottom: 20px;
        }

        .todo-list {
            max-width: 800px;
            margin: 0 auto;
            background: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .filterStatus {            
            margin: auto;
            max-width: 200px;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            align-content: center;
            margin-bottom: 8px;
        }

        .task {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
            border-bottom: 5px solid #ddd;
            transition: background-color 0.3s ease;
        }

        .task:last-child {
            border-bottom: none;
        }

        .task:hover {
            background-color: #f9f9f9;
        }

        .task-expired {
            background: #FAA0A0;
        }

        .task-details {
            display: flex;
            flex-direction: column;
            max-width: 50%;
        }

        .task-name {
            font-size: 1.2em;
            font-weight: bold;
            color: #333;
        }

        .task-description {
            font-size: 0.9em;
            color: #777;
        }

        .task-status-link {
            color: white;
            text-decoration: none;
            
        }

        .task-status {
            padding: 6px 12px;
            border-radius: 15px;
            font-size: 0.9em;
        }

        /* Status Colors */
        .status-todo {
            background-color: #f39c12;
            color: white;
        }

        .status-inprogress {
            background-color: #3498db;
            color: white;
        }

        .status-done {
            background-color: #2ecc71;
            color: white;
        }

        .task-due {
            font-size: 0.9em;
            color: #555;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #4a90e2;
            color: white;
            text-align: center;
            cursor: pointer;
            margin-top: 10px;
            transition: background-color 0.3s ease;
        }
        
        .btn:hover {
            background-color: #357ABD;
        }

        media screen and (max-width: 600px) {
            .task {
                flex-direction: column;
                align-items: flex-start;
            }

            .task-details {
                max-width: 100%;
            }

            .task-status {
                margin-top: 10px;
            }
        }
    </style>
</head>
<body>
    <h1>My ToDo List</h1>
    <div class="filterStatus">
        <form asp-action="Index" method="get">
            <input type="checkbox" id="IncludeToDo" name="status" value="@((byte)ToDoStates.ToDo)" @((ViewData["CurrentStatusFilters"] as List<byte>)?.Contains((byte)ToDoStates.ToDo) == true ? "checked" : "") />
            <label for="IncludeToDo">ToDo</label>
            <br />
            <input type="checkbox" id="IncludeInProgress" name="status" value="@((byte)ToDoStates.InProgress)" @((ViewData["CurrentStatusFilters"] as List<byte>)?.Contains((byte)ToDoStates.InProgress) == true ? "checked" : "") />
            <label for="IncludeInProgress">InProgress</label>
            <br />
            <input type="checkbox" id="IncludeDone" name="status" value="@((byte)ToDoStates.Done)" @((ViewData["CurrentStatusFilters"] as List<byte>)?.Contains((byte)ToDoStates.Done) == true ? "checked" : "")/>
            <label for="IncludeDone">Done</label>
            <br />
            <button type="submit">Filter</button>
        </form>
    </div>
    <div class="todo-list">
        @foreach (var task in Model)
        {
            <div class="task @(IsTaskExpired(task.DueDate, task.StatusCode))">
                <div class="task-details">
                    <span class="task-name">@task.Name</span>
                    <span class="task-description">@task.Description</span>
                </div>
                <div class="task-status @GetStatusClass((task.StatusCode))">
                    <a class="task-status-link" asp-action="ChangeStatus" asp-route-id="@task.Id">@Enum.GetName(typeof(ToDoStates), task.StatusCode)</a>
                </div>
                <div class="task-due">
                    Due: @task.DueDate
                </div>
                <div>
                    <a class="btn" asp-action="Edit" asp-route-id="@task.Id"><i class="fa fa-edit"></i></a>
                    <a class="btn" asp-action="Delete" asp-route-id="@task.Id"><i class="fa fa-trash"></i></a>
                </div>
                
            </div>
        }
    </div>

    <div style="text-align: center;">
        <a asp-action="Create" class="btn">Add New Task</a>
    </div>

    @functions {
        // Helper method to assign status class
        string GetStatusClass(byte? statusCode)
        {
            switch ((ToDoStates)statusCode)
            {
                case ToDoStates.ToDo:
                    return "status-todo";
                case ToDoStates.InProgress:
                    return "status-inprogress";
                case ToDoStates.Done:
                    return "status-done";
                default:
                    return "";
            }
        }

        string IsTaskExpired(DateOnly? dueDate, byte? statusCode)
        {            
            if ((dueDate < DateOnly.FromDateTime(DateTime.Now)) && (statusCode != (byte)ToDoStates.Done))
            {
                return "task-expired";
            }
            return "";
        }
    }
</body>
</html>